# Generated by Django 5.2.2 on 2025-11-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('total_results', models.IntegerField()),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
